# Calendar Management is an embedded, local-first app.

client_id = "0f25395dffd9e4cb946667e964fda31f"
application_url = "https://calendar-management-2.halinh280107.workers.dev"
name = "Calendar Management"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[app_preferences]
url = "https://calendar-management-2.halinh280107.workers.dev"
